[general]
conf_file_param = "conf"

[[param]]
name = "address"
type = "String"
optional = false
doc = "LND GRPC address, kindly note that the address must start with https:// ip address : port."

[[param]]
name = "cert_path"
type = "std::path::PathBuf"
optional = true
doc = "The path to LND tls certificate file. Note: the abosolute tls certificate file path is required here."

[[param]]
name = "cert_pem"
type = "String"
optional = true
doc = "The PEM-encoded tls certificate to pass directly into LNDK."

[[param]]
name = "tls_ip"
type = "String"
optional = true
doc = "Add an ip or domain to the certificate used to access the LNDK server. To add multiple ip addresses, separate each ip address with a comma. Like: '192.168.0.1,lndkisdope.org'"

[[param]]
name = "macaroon_path"
type = "std::path::PathBuf"
optional = true
doc = "The path to LND macaroon file. Note: the abosolute macaroon file path is required here."

[[param]]
name = "macaroon_hex"
type = "String"
optional = true
doc = "The hex encoded macaroon to pass directly into LNDK"

[[param]]
name = "log_dir"
type = "String"
doc = "The path to the lndk log file. By default this is stored in ~/.lndk"

[[param]]
name = "log_level"
type = "String"
optional = true
doc = "The log verbosity level. This can be set to either 'error', 'warn', 'info', 'debug' or 'trace'."

[[param]]
name = "grpc_host"
type = "String"
optional = true
doc = "The host the grpc server will run on. Defaults to 127.0.0.1."

[[param]]
name = "grpc_port"
type = "u16"
optional = true
doc = "The port the grpc server will run on. Defaults to 7000."

[[param]]
name = "skip_version_check"
type = "bool"
default = "false"
doc = "Skip checking the LND version. Otherwise, LNDK checks that the LND version is compatible with LNDK."

[[param]]
name = "response_invoice_timeout"
type = "u32"
optional = true
doc = "Amount of time in seconds that server waits for an offer creator to respond with an invoice. Defaults to 15s."
